### PR TITLE
Ported to python 3.8

### PR DESCRIPTION
**Pull request by tofu13**

### CODE REVIEW

**Comment by tofu13** [comment]
Hi, I'm interested in continuing your project.

**Comment by fabioanderegg** [comment]
Hi! I do not have plans right now to continue this project. I propose to archive this repo here and link to your fork if that is ok?

**Comment by fotcorn** [comment]
Hi! I do not have plans right now to continue this project. I propose to archive this repo here and link to your fork if that is ok?

**Comment by tofu13** [comment]
Hi Fabio, sorry for the late reply.
I started a new project at https://github.com/tofu13/pyc64 .
I'd really appreciate a link to this project, which took inspiration from
your work (you're the first in the credits list).

Thank you again, bye!
Marco


Il giorno mer 17 feb 2021 alle ore 10:41 Fabio Anderegg <
notifications@github.com> ha scritto:

**Comment by fotcorn** [comment]
Done!

Thanks and good luck with your project!

**Pull request closed without merging**
